### ISSUE TITLE
Align comments to comply with google cpplint

### ISSUE THREAD

**Issue by sittim** [godlygeek/tabular#44]
Any way to enter a command to format comments to be compliant to googles cpplint?

![selection_086](https://cloud.githubusercontent.com/assets/8825037/12989202/4ba54dd2-d0d2-11e5-92e1-295f70091f79.png)

Top section is not compliant, to comply 5 changes are required.

1. keep this comment at the same level
2. Add a space after `//` 
3. add minimum of two spaced between code and comment
4. align comments
5. add space after `//`

**Comment by HuStmpHrrr** [comment]
it can be done:

```
:Tabularize /^.\{-\}\zs\/\//l2c1l0
```

haven't really tried. but it should more or less work. explanation:

`^.\{-\}\zs\/\/` -- match everything before the first `//`, and then reset the matching pointer, such that it makes vim thinks the matching start right before `//`
`l2c1l0` -- things before `//` left aligned, 2 spaces, `//` central aligned, 1 space, the rest left aligned.

for more, check out `:help tabular`.

**Comment by sittim** [comment]
It did not work, does the same thing as `Tab////`

**Comment by godlygeek** [comment]
This is deceptively difficult.  The problem is that you're trying to treat // in two different ways depending on whether or not there is non-whitespace text before it, and in each case you want to perform different actions.  That's not something that can be done with a single :Tabularize command.

It can be done by running two GTabularize commands, though, that each explicitly match a separate subset of lines:

    :GTabularize /^\s*\zs\/\//l0l1
    :GTabularize /^.\{-}\S.\{-}\zs\/\//l2l1

The first of those says "for lines that start with // (ignoring any leading whitespace) ensure there is exactly one space after the //".

The second one says "for lines that have a // but that have at least one non-whitespace character before the // ensure that there are two spaces before and one after the //".

And you can combine those two into a single named command using something like:

    :AddTabularPipeline! cpplint_comments /\/\// tabular#TabularizeStrings(a:lines, '^.\{-}\S.\{-}\zs//', 'l2l1') | tabular#TabularizeStrings(a:lines, '^\s*\zs\/\/', 'l0l1')

Which would allow you to get the effect you're looking for by just running:

    :GTabularize cpplint_comments

You could optionally provide a range to that in order to have it act on only a subset of the buffer.

**Comment by sittim** [comment]
Thanks, but for such complex task ClangFormat works great is a more suitable tool, so I have been using that.
